version: '3'
services:
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    volumes:
      - ./config-ep/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./config-default:/fluent-bit/configs/config-default
      - ./config-ep:/fluent-bit/configs/config-ep
      - ./sample.log:/var/log/test.log
      - ../logs:/var/logs/default
      - /c/epshil/.logs/HILTest:/var/logs/HILTest
    networks:
      - opensearch-net

networks:
  opensearch-net:
    external: true
