version: '3'
services:
  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./sample.log:/var/log/test.log
    networks:
      - opensearch-net

networks:
  opensearch-net:
    external: true
